// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sim_mc
arma::vec sim_mc(int n, arma::mat P, int start);
RcppExport SEXP MCMCprec_sim_mc(SEXP nSEXP, SEXP PSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_mc(n, P, start));
    return rcpp_result_gen;
END_RCPP
}
// rdirichletPt
arma::sp_mat rdirichletPt(arma::sp_mat Pt);
RcppExport SEXP MCMCprec_rdirichletPt(SEXP PtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type Pt(PtSEXP);
    rcpp_result_gen = Rcpp::wrap(rdirichletPt(Pt));
    return rcpp_result_gen;
END_RCPP
}
// stationaryCpp
arma::mat stationaryCpp(arma::mat freq, int iter);
RcppExport SEXP MCMCprec_stationaryCpp(SEXP freqSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(stationaryCpp(freq, iter));
    return rcpp_result_gen;
END_RCPP
}
// stationaryCppSparse
arma::mat stationaryCppSparse(arma::sp_mat freq, int iter);
RcppExport SEXP MCMCprec_stationaryCppSparse(SEXP freqSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(stationaryCppSparse(freq, iter));
    return rcpp_result_gen;
END_RCPP
}
